name: Analytics
on: workflow_dispatch

jobs:
  pester-test:
    name: validate detections
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Validate Sentinel Analytics Rules
        uses: SecureHats/validate-detections@v1.1
        with:
          filesPath: ./packages/azure-ad
          logLevel: Minimal
