on: [push]
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main
      # Load variables
    
      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run: |
        Get-Content './environments/nonprod.yml' >> $Env:GITHUB_ENV   # <- Adding directly $Env:GITHUB_ENV saves at the workflow level
      shell: pwsh
    - uses: './environments/nonprod.yml'
    
      # Deploy ARM template
    - name: Create Log Analytics workspace
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ env.sentinelResourceGroup }}
        template: ./resources/workspace.bicep
        parameters: workspaceName=${{ env.workspaceName }}
    
    - name: Enable Microsoft Sentinel
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ env.sentinelResourceGroup }}
        template: ./resources/security-insights.bicep
        parameters: workspaceName=${{ env.workspaceName }}

      # output containerName variable from template.
    - run: echo ${{ steps.deploy.outputs.containerName }}
