name: Build and Publish Sentinel Solutions
on: [push]
jobs:        
  build-and-deploy:
    runs-on: ubuntu-latest
    outputs:
      customerSolutions: ${{ env.customerSolutions }}
      list: ${{ steps.step2.outputs.list }}
    steps:

      # Checkout code
    - uses: actions/checkout@main
      
      # Load variables
    - name: Set Variables
      uses: SecureHats/JsonTo-Variable@v0.0.20
      id: step1
      with:
        filePath: './environments/nonprod.json'
        arraySeparator: ';'
        outputs: $true
      
    - name: Create Json Array
      id: step2
      run: |
          $arrayList = "${{ env.customerSolutions }}" -split ';' | ConvertTo-Json -Compress
          echo $arrayList
          echo "::set-output name=list::$arrayList"
      shell: pwsh
      
      #  Log into Azure
#     - uses: azure/login@v1
#       with:
#         creds: ${{ secrets.AZURE_CREDENTIALS }}
    
#       # Deploy ARM template
#     - name: Create Log Analytics workspace
#       uses: azure/arm-deploy@v1
#       with:
#         subscriptionId:    ${{ secrets.AZURE_SUBSCRIPTION }}
#         resourceGroupName: ${{ env.sentinelResourceGroup }}
#         template:          "./resources/workspace.bicep"
#         parameters:        "workspaceName=${{ env.workspaceName }}"
    
#     - name: Enable Microsoft Sentinel
#       uses: azure/arm-deploy@v1
#       with:
#         subscriptionId:    ${{ secrets.AZURE_SUBSCRIPTION }}
#         resourceGroupName: ${{ env.sentinelResourceGroup }}
#         template:          "./resources/security-insights.bicep"
#         parameters:        "workspaceName=${{ env.workspaceName }}"
      
  example_matrix:
    strategy:
      matrix:
        package: ${{ fromJSON(needs.build-and-deploy.outputs.list ) }}
    runs-on: ubuntu-latest
    needs: build-and-deploy
      
    steps:
      # Checkout code
      - uses: actions/checkout@main
    
      - name: Echo previous outputs
        run: echo "${{ toJSON(needs.build-and-deploy.outputs.array) }}"
      
      - name: Set Variables
        uses: SecureHats/JsonTo-Variable@v0.0.20
        with:
          filePath: './environments/nonprod.json'
          arraySeparator: ';'
          outputs: $false
      
      - name: Enumerate files
        id: get-files
        run: | 
            $files = (Get-ChildItem -path ./packages/${{ matrix.package }} -Include "*.json" -Recurse).FullName | ConvertTo-Json -Compress
            echo "files=$files" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        shell: pwsh

      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Run Azure PowerShell script
        uses: azure/powershell@v1
        with:
          inlineScript: |
            foreach ($file in ${{ fromJson(env.files) }} ) {
              Write-Output "show parsed files:" $file
            }
            
          #  foreach ($template in ${{ fromJSON(env.files) }})
          #   New-AzResourceGroupDeployment -name "${{ matrix.package }}" -ResourceGroupName "${{ env.sentinelResourceGroup }}" -TemplateFile  $template -workspace "${{ env.workspaceName }}"
          azPSVersion: "latest"

      # - uses: azure/arm-deploy@v1
      #   with:
      #     subscriptionId:    ${{ secrets.AZURE_SUBSCRIPTION }}
      #     resourceGroupName: ${{ env.sentinelResourceGroup }}
      #     template:          "./packages/${{ matrix.package }}/template.json"
      #     parameters:        "workspace=${{ env.workspaceName }}"
