on: [push]
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
    - name: Create Log Analytics workspace
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: '329ce62c-c677-4f9c-9266-0dcefa7eac1e-rg'
        template: ./resources/workspace.bicep
        parameters: workspaceName = 'rdk-workspace-bicep'
    
    - name: Enable Microsoft Sentinel
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: '329ce62c-c677-4f9c-9266-0dcefa7eac1e-rg'
        template: ./resources/security-insights.bicep
        parameters: workspaceName = 'rdk-workspace-bicep'

      # output containerName variable from template.
    - run: echo ${{ steps.deploy.outputs.containerName }}
