name: Build and Publish Sentinel Solutions
on:
  push:
    paths:
      - '.github/workflows/**'
jobs:        
  set-variables:
    runs-on: ubuntu-latest
    outputs:
      customerSolutions:     ${{ env.customerSolutions }}
      sentinelResourceGroup: ${{ env.sentinelResourceGroup }}
      workspaceName:         ${{ env.workspaceName }}
      location:              ${{ env.location }}
  
    steps:
      # Checkout code
    - uses: actions/checkout@main
      
      # Load variables
    - name: Set Variables
      uses: SecureHats/JsonTo-Variable@v0.1.3
      id: build-variable
      with:
        filePath:       './environments/nonprod.json'
        outputs:        $true
 
  deploy-resources:
    runs-on: ubuntu-latest
    needs: set-variables
    steps:
      #  Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      # Checkout code
    - uses: actions/checkout@main

      # Deploy ARM template
    - name: Create Resource Group
      uses: azure/arm-deploy@v1
      with:
        subscriptionId:    ${{ secrets.AZURE_SUBSCRIPTION }}
        scope:             'subscription'
        region:            ${{ needs.set-variables.outputs.location }}
        template:          "./resources/resourcegroup.bicep"
        parameters:        "resourceGroupName=${{ needs.set-variables.outputs.sentinelResourceGroup }} location=${{ needs.set-variables.outputs.location }}"
    
    - name: Create Log Analytics workspace
      uses: azure/arm-deploy@v1
      with:
        subscriptionId:    ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ needs.set-variables.outputs.sentinelResourceGroup }}
        template:          "./resources/workspace.bicep"
        parameters:        "workspaceName=${{ needs.set-variables.outputs.workspaceName }}"
    
    - name: Enable Microsoft Sentinel
      uses: azure/arm-deploy@v1
      with:
        subscriptionId:    ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ needs.set-variables.outputs.sentinelResourceGroup }}
        template:          "./resources/security-insights.bicep"
        parameters:        "workspaceName=${{ needs.set-variables.outputs.workspaceName }}"
      
  deploy_analytics:
    strategy:
      matrix:
        package: ${{ fromJSON(needs.set-variables.outputs.customerSolutions ) }}
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: 
      - deploy-resources
      - set-variables
      
    steps:
      # Checkout code
      - uses: actions/checkout@main
          
      - name: Validate Deprecated KQL values
        uses: SecureHats/kusto-alias@v0.1.5-alpha
        with:
          filesPath: ./packages/${{ matrix.package }}
          logLevel: Minimal
          
      - name: Convert Template files
        uses: SecureHats/YamlTo-Arm@v0.1.7
        with:
          filesPath:  ./packages/${{ matrix.package }}
          outputPath: ./packages/${{ matrix.package }}
          
      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy Analytics
        uses: azure/arm-deploy@v1
        with:
          subscriptionId:    ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: "${{ needs.set-variables.outputs.sentinelResourceGroup }}"
          template:          "./packages/${{ matrix.package }}/deployment.json"
          parameters:        "workspace=${{ needs.set-variables.outputs.workspaceName }}"
