name: Build and Publish Sentinel Solutions
on:
  push:
    paths:
      - 'environments/**'
jobs:        
  build-and-deploy:
    runs-on: ubuntu-latest
    outputs:
      customerSolutions: ${{ env.customerSolutions }}
      list: ${{ steps.step2.outputs.list }}
      sentinelResourceGroup: ${{ env.sentinelResourceGroup }}
      workspaceName: ${{ steps.step1.outputs.workspaceName }}
    steps:

      # Checkout code
    - uses: actions/checkout@main
      
      # Load variables
    - name: Set Variables
      uses: SecureHats/JsonTo-Variable@v0.0.20
      id: step1
      with:
        filePath: './environments/nonprod.json'
        arraySeparator: ';'
        outputs: $true
      
    - name: Create Json Array
      id: step2
      run: |
          $arrayList = "${{ env.customerSolutions }}" -split ';' | ConvertTo-Json -Compress
          echo $arrayList
          echo "list=$arrayList" >> $env:GITHUB_OUTPUT
      shell: pwsh
      
      #  Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      # Deploy ARM template
    - name: Create Log Analytics workspace
      uses: azure/arm-deploy@v1
      with:
        subscriptionId:    ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ env.sentinelResourceGroup }}
        template:          "./resources/workspace.bicep"
        parameters:        "workspaceName=${{ env.workspaceName }}"
    
    - name: Enable Microsoft Sentinel
      uses: azure/arm-deploy@v1
      with:
        subscriptionId:    ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ env.sentinelResourceGroup }}
        template:          "./resources/security-insights.bicep"
        parameters:        "workspaceName=${{ env.workspaceName }}"
      
  deploy_analytics:
    strategy:
      matrix:
        package: ${{ fromJSON(needs.build-and-deploy.outputs.list ) }}
    runs-on: ubuntu-latest
    needs: build-and-deploy
      
    steps:
      # Checkout code
      - uses: actions/checkout@main
    
      # - name: Echo previous outputs
      #   run: echo "${{ toJSON(needs.build-and-deploy.outputs.list) }}"
      
      # - name: Set Variables
      #   uses: SecureHats/JsonTo-Variable@v0.0.20
      #   with:
      #     filePath: './environments/nonprod.json'
      #     arraySeparator: ';'
      #     outputs: $false
          
      - name: Convert Template files
        uses: SecureHats/YamlTo-Arm@v0.1.7
        with:
          filesPath: ./packages/${{ matrix.package }}
          outputPath: ./packages/${{ matrix.package }}
#           singleFile: $true
          
      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
#           enable-AzPSSession: true
          
      - name: Deploy Analytics
        uses: azure/arm-deploy@v1
        with:
          subscriptionId:    ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ needs.build-and-deploy.outputs.sentinelResourceGroup }} # ${{ env.sentinelResourceGroup }}
          template:          "./packages/${{ matrix.package }}/deployment.json"
          parameters:        ${{ needs.build-and-deploy.outputs.workspaceName }} #"workspace=${{ env.workspaceName }}"
