on: [push]
name: Azure ARM
jobs:
          
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main
      
      # Load variables
    - name: Set Variables
      uses: SecureHats/JsonTo-Variable@v0.0.20
      with:
        filePath: './environments/nonprod.json'
        arraySeparator: ','
        outputs: $false
    
      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      # Deploy ARM template
    - name: Create Log Analytics workspace
      uses: azure/arm-deploy@v1
      with:
        subscriptionId:    ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ env.sentinelResourceGroup }}
        template:          "./resources/workspace.bicep"
        parameters:        "workspaceName=${{ env.workspaceName }}"
    
    - name: Enable Microsoft Sentinel
      uses: azure/arm-deploy@v1
      with:
        subscriptionId:    ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ env.sentinelResourceGroup }}
        template:          "./resources/security-insights.bicep"
        parameters:        "workspaceName=${{ env.workspaceName }}"
