name: Build and Publish Sentinel Solutions
on:
  push:
    paths:
      - '.github/workflows/**'
jobs:        
  set-variables:
    runs-on: ubuntu-latest
    outputs:
      customerSolutions:     ${{ env.packages_customerSolutions }}
      sentinelResourceGroup: ${{ env.LogAnalytics_sentinelResourceGroup }}
      workspaceName:         ${{ env.LogAnalytics_workspaceName }}
      location:              ${{ env.LogAnalytics_location }}
      solutionsPath:         ${{ env.packages_solutionsPath }}
      pricingTierLogAnalytics:           ${{ env.LogAnalytics_pricingTierLogAnalytics }}
      pricingTierSentinel:               ${{ env.LogAnalytics_pricingTierSentinel }}
      capacityReservationLevelSentinel:  ${{ env.LogAnalytics_capacityReservationLevelSentinel }}
      retentionInDays:                   ${{ env.LogAnalytics_retentionInDays }}
      enableBehaviorAnalyticsInsights:   ${{ env.LogAnalytics_enableBehaviorAnalyticsInsights }}
      enableLogicAppsManagementInsights: ${{ env.LogAnalytics_enableLogicAppsManagementInsights }}
      enableDnsAnalytics:                ${{ env.LogAnalytics_enableDnsAnalytics }}
      enableContainerInsights:           ${{ env.LogAnalytics_enableContainerInsights }}
      enableVMInsights:                  ${{ env.LogAnalytics_enableVMInsights }}
      enableWindowsFirewall:             ${{ env.LogAnalytics_enableWindowsFirewall }}
  
    steps:
      # Checkout code
    - uses: actions/checkout@main
      
      # Load variables
    - name: Set Variables
      uses: SecureHats/JsonTo-Variable@v0.1.3
      id: build-variable
      with:
        filePath: './environments/nonprod.json'
        outputs:  $true
 
  deploy-resources:
    runs-on: ubuntu-latest
    needs: set-variables
    steps:
      #  Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      # Checkout code
    - uses: actions/checkout@main

      # Deploy ARM template
    - name: Create Resource Group
      uses: azure/arm-deploy@v1
      with:
        subscriptionId:    ${{ secrets.AZURE_SUBSCRIPTION }}
        scope:             'subscription'
        region:            ${{ needs.set-variables.outputs.location }}
        template:          "./resources/resourcegroup.bicep"
        parameters:        "resourceGroupName=${{ needs.set-variables.outputs.sentinelResourceGroup }} location=${{ needs.set-variables.outputs.location }}"
    
    - name: Create Log Analytics workspace
      uses: azure/arm-deploy@v1
      with:
        subscriptionId:    ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ needs.set-variables.outputs.sentinelResourceGroup }}
        template:          "./resources/workspace.bicep"
        parameters:        "workspaceName=${{ needs.set-variables.outputs.workspaceName }}"
        
    - name: Create Log Analytics workspace
      uses: azure/arm-deploy@v1
      with:
        subscriptionId:    ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ needs.set-variables.outputs.sentinelResourceGroup }}
        template:          "./resources/solutions.bicep"
        parameters:        "logAnalyticsName=${{ needs.set-variables.outputs.workspaceName }} location=${{ needs.set-variables.outputs.location }} retentionInDays=${{ needs.set-variables.outputs.retentionInDays }} enableBehaviorAnalyticsInsights=${{ needs.set-variables.outputs.enableBehaviorAnalyticsInsights }} enableLogicAppsManagementInsights=${{ needs.set-variables.outputs.enableLogicAppsManagementInsights }} enableDnsAnalytics=${{ needs.set-variables.outputs.enableDnsAnalytics }} enableContainerInsights=${{ needs.set-variables.outputs.enableContainerInsights }} enableVMInsights=${{ needs.set-variables.outputs.enableVMInsights }}"
      
  deploy_analytics:
    strategy:
      matrix:
        package: ${{ fromJSON(needs.set-variables.outputs.customerSolutions ) }}
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: 
      - deploy-resources
      - set-variables
      
    steps:
      # Checkout code
      - uses: actions/checkout@main
          
      - name: Convert Template files
        uses: SecureHats/YamlTo-Arm@v0.1.7
        with:
          filesPath:  ./${{ needs.set-variables.outputs.solutionsPath }}/${{ matrix.package }}
          outputPath: ./${{ needs.set-variables.outputs.solutionsPath }}/${{ matrix.package }}
          
      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy Analytics
        uses: azure/arm-deploy@v1
        with:
          subscriptionId:    ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: "${{ needs.set-variables.outputs.sentinelResourceGroup }}"
          template:          "./${{ needs.set-variables.outputs.solutionsPath }}/${{ matrix.package }}/deployment.json"
          parameters:        "workspace=${{ needs.set-variables.outputs.workspaceName }}"