name: Build and Publish Sentinel Solutions
on: [push]
jobs:        
  build-and-deploy:
    runs-on: ubuntu-latest
    outputs:
      customerSolutions: ${{ env.customerSolutions }}
      list: ${{ steps.step2.outputs.list }}
    steps:

      # Checkout code
    - uses: actions/checkout@main
      
      # Load variables
    - name: Set Variables
      uses: SecureHats/JsonTo-Variable@v0.0.20
      id: step1
      with:
        filePath: './environments/nonprod.json'
        arraySeparator: ';'
        outputs: $true
      
    - name: Create Json Array
      id: step2
      run: |
          $arrayList = "${{ env.customerSolutions }}" -split ';' | ConvertTo-Json -Compress
          echo $arrayList
          echo "::set-output name=list::$arrayList"
      shell: pwsh
      
      #  Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      # Deploy ARM template
    - name: Create Log Analytics workspace
      uses: azure/arm-deploy@v1
      with:
        subscriptionId:    ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ env.sentinelResourceGroup }}
        template:          "./resources/workspace.bicep"
        parameters:        "workspaceName=${{ env.workspaceName }}"
    
    - name: Enable Microsoft Sentinel
      uses: azure/arm-deploy@v1
      with:
        subscriptionId:    ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ env.sentinelResourceGroup }}
        template:          "./resources/security-insights.bicep"
        parameters:        "workspaceName=${{ env.workspaceName }}"
      
  deploy_analytics:
    strategy:
      matrix:
        package: ${{ fromJSON(needs.build-and-deploy.outputs.list ) }}
    runs-on: ubuntu-latest
    needs: build-and-deploy
      
    steps:
      # Checkout code
      - uses: actions/checkout@main
    
      - name: Echo previous outputs
        run: echo "${{ toJSON(needs.build-and-deploy.outputs.list) }}"
      
      - name: Set Variables
        uses: SecureHats/JsonTo-Variable@v0.0.20
        with:
          filePath: './environments/nonprod.json'
          arraySeparator: ';'
          outputs: $false
      
      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Convert Template files
        uses: SecureHats/YamlTo-Arm@v0.1.0
        with:
          filesPath: ./packages/${{ matrix.package }}
          outputPath: ./packages/${{ matrix.package }}
          singleFile: $false
          debugging: $false
          
      - name: Deploy Analytics
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $files = (Get-ChildItem -path ./packages/${{ matrix.package }} -Include "*.json" -Recurse)            
            write-output "files found: $($files.count)"
            Get-ChildItem -path ./packages/${{ matrix.package }} -Include "*.json" -Recurse
            foreach ($template in $files) {
            Write-Output "file is: $($template.FullName)"
              $deploymentHash = @{
                "name"              = "${{ matrix.package }}"
                "resourceGroupName" = "${{ env.sentinelResourceGroup }}"
                "workspace"         = "${{ env.workspaceName }}"
                "templateFile"      = "$($template.FullName)"
              }
              New-AzResourceGroupDeployment @deploymentHash
            }
          azPSVersion: "latest"
