on: [push]
name: Azure ARM
jobs:
          
  build-and-deploy:
    runs-on: ubuntu-latest
    outputs:
      customerSolutions: ${{ env.customerSolutions }}
      array: ${{ env.arrayList }}
    steps:

      # Checkout code
    - uses: actions/checkout@main
      
      # Load variables
    - name: Set Variables
      uses: SecureHats/JsonTo-Variable@v0.0.20
      id: step1
      with:
        filePath: './environments/nonprod.json'
        arraySeparator: ';'
        outputs: $true
      
    - name: Create Json Array
      id: array
      run: |
          $arrayList = "${{ env.customerSolutions }}" -split ';' | ConvertTo-Json
          echo $arrayList
          echo "arrayList=$arrayList" >> $GITHUB_OUTPUT
      shell: pwsh
      
      #  Log into Azure
#     - uses: azure/login@v1
#       with:
#         creds: ${{ secrets.AZURE_CREDENTIALS }}
    
#       # Deploy ARM template
#     - name: Create Log Analytics workspace
#       uses: azure/arm-deploy@v1
#       with:
#         subscriptionId:    ${{ secrets.AZURE_SUBSCRIPTION }}
#         resourceGroupName: ${{ env.sentinelResourceGroup }}
#         template:          "./resources/workspace.bicep"
#         parameters:        "workspaceName=${{ env.workspaceName }}"
    
#     - name: Enable Microsoft Sentinel
#       uses: azure/arm-deploy@v1
#       with:
#         subscriptionId:    ${{ secrets.AZURE_SUBSCRIPTION }}
#         resourceGroupName: ${{ env.sentinelResourceGroup }}
#         template:          "./resources/security-insights.bicep"
#         parameters:        "workspaceName=${{ env.workspaceName }}"
      
  example_matrix:
    strategy:
      matrix:
        package: ${{ fromJSON(needs.build-and-deploy.outputs.array ) }}
    runs-on: ubuntu-latest
    needs: build-and-deploy
      
    steps:
      # Checkout code
      - uses: actions/checkout@main
    
      - name: Echo previous outputs
        run: echo "${{ toJSON(needs.build-and-deploy.outputs.array) }}"
      
      - name: Set Variables
        uses: SecureHats/JsonTo-Variable@v0.0.22
        with:
          filePath: './environments/nonprod.json'
          arraySeparator: ';'
          outputs: $false
        
      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - uses: azure/arm-deploy@v1
        with:
          subscriptionId:    ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ env.sentinelResourceGroup }}
          template:          "./packages/${{ matrix.package }}/template.json"
          parameters:        "workspace=${{ env.workspaceName }}"
