name: template
on:
  push:
    paths:
      - samples/**

jobs:
  template:
    name: YamlTo-ARM
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: SecureHats template
        uses: SecureHats/YamlTo-Arm@v1.0
        with:
          filesPath: samples
          outputPath: output
